services:
  synkro-workflow:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    environment:
      SERVER_PORT: "8080"
    expose: ["8080"]
    networks: [platform]

networks:
  platform:
    external: true
